### PR TITLE
Added norwegian language #3

### PR DESCRIPTION
**Pull request by jangerhard**

### CODE REVIEW

**Comment by mnirfan** [comment]
hello @jangerhard, thanks for your PR. But i think you should replace dash `-` with underscore `_` in your locale folder name. And also some changes in `default.po` line 12 :)

**Comment by jangerhard** [comment]
Fixed!

**Comment by mnirfan** [comment]
I think it should be `no_NO` instead of `no_no` :)

**Comment by jangerhard** [comment]
It is fixed now :+1:

**Comment by mnirfan** [comment]
Nice! thanks @jangerhard :)

**Pull request merged**
