### PR TITLE
Added Turkish

### PR DESCRIPTION
**Pull request by dkarakay**
Happy HacktoberFest! #3

### CODE REVIEW

**Comment by mnirfan** [comment]
thanks for the PR @dkarakay, but i dont see any translation. am i miss something?

**Comment by dkarakay** [comment]
@mnirfan Wait I'll check ASAP

**Comment by dkarakay** [comment]
Now, you should see :) @mnirfan

**Comment by mnirfan** [comment]
awesome! thanks for your contribution @dkarakay :)

**Pull request merged**
