### PR TITLE
Added spanish

### PR DESCRIPTION
**Pull request by rocketsalander**

### CODE REVIEW

**Comment by mnirfan** [comment]
thanks for your PR, @SioJL13, but i think your locale code is incorrect. I think it is `es_MX` instead of `id_es_MX`. and what is ` .DS_Store` file? maybe it's better to remove it from PR :)

**Comment by rocketsalander** [comment]
I changed it and deleted DS_Store, maybe I can create a gitignore to avoid the DS_Store that mac computers implement by default. @mnirfan

**Review by mnirfan — CHANGES_REQUESTED** [review]
oh, my bad. i think you should also change the `"Language: id_ID"` in line 12.

**Comment by rocketsalander** [comment]
Done @mnirfan :)

**Review by mnirfan — APPROVED** [review]

**Comment by mnirfan** [comment]
Awesome! thanks @SioJL13 :)

**Pull request merged**
